language: node_js

node_js: lts/*

cache:
  directories:
    - node_modules

branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_a99f0ed79e16_key -iv $encrypted_a99f0ed79e16_iv -in .travis/imciel-deployer.enc -out  ~/.ssh/imciel-deployer -d
- chmod 600 ~/.ssh/imciel-deployer
- eval $(ssh-agent)
- ssh-add ~/.ssh/imciel-deployer
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "cielpy"
- git config --global user.email "beijiu572@gmail.com"

- git clone https://github.com/cielpy/hexo-theme-even.git themes/hexo-theme-even

- npm install -g hexo-cli
- npm install -g yarn
install:
- yarn install
script:
- hexo generate
after_success:
- hexo deploy
