language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- git submodule init
- git submodule update
- hexo generate
after_success:
- git config --global user.name "cielpy"
- git config --global user.email "beijiu572@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy > log
- rm -f log
env:
  global:
    secure: Cy9ikz9rgoxNLDt3hCwjeA4HaOXeeE306BWMSpcf2jIPaHszx8jXKf7b7yv8iFe4xRWuad8iOHwC2wZpZWYFARrB/SAP+JqJ9p4RL9zUeuiyhc4z2bI9qUkefyclijTjVeG4o6MOGu8UyV9f7O6b4t3ydUbvTU24CtMY5NIPcunWNjdf2G1N/RezRZK/StnJpmTggtqwnAXu7bo4SvJAcrsGudfsryusJdWtmgEgBeuVfvMD+BtzYNiIiTyogG7OdObJZ+gFilGbBSg3on8nNoF7l/QqN5EFhReTTkYDDI70/aFXDdQGGR8h+kIj7BYVwpvY1zZyal8eu28yGd+PjWiMIAZuHy1skbFFR2dX88wVkVNQE5rmyTqmh9TJXg5YnOFqY4exEk5LXIrgG26wW0ydi1+raHbIiXg7S1tZbdMLSgoN6ejXbUVZVntOxsUU8QgBKTbWpmVaJEFVem5lk6bv2ve3M5PL2eIFDU+OdFcXWP4NOerJVJUjMEk+Su1bREoGJsh57MAU5cO9ZO0Q0t5znf3CRrxCpML90T7C8kiqgRTQ5WQc2cQwXN8uFfZ4RnvpQ6x2LmqPKJ7fFB6NI4AopExYomphQad6CYR1hoJU6ePsox7AagOuc/CFFmiSxtf13yaPOa//euQpp/zaDlpWtoLH8lIr8P3qwWW30ZE=
